# Generated by Django 3.1.2 on 2020-10-24 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kurasi', '0002_auto_20201024_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
