# Generated by Django 3.1.2 on 2020-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurasi', '0003_input_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
